name: ilu
version: 1.0.0+1
publish_to: none
description: Explore, Connect and share your Interests with real people.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.2.0
  get: 4.6.6
  cached_network_image: ^3.3.1
  google_fonts: 
  flutter_svg: ^2.0.10+1
  simple_gradient_text: ^1.3.0
  gap:
  image_picker: ^1.0.7
  gradient_borders: ^1.0.0
  dotted_border:
  gradient_icon: ^2.0.9
  flutter_slidable: ^3.0.1
  camera:
  camera_web: ^0.3.2+4
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  shared_preferences:
  file_picker:
  popover:
  toggle_switch: ^2.3.0
  api_service_interceptor: ^3.0.0
  fluttertoast:
  intl:
  firebase_auth:
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.2
  permission_handler: ^11.3.1
  agora_rtc_engine: ^6.3.0
  agora_rtm: ^1.5.9
  url_strategy: ^0.2.0
  flutter_emoji: ^2.5.1
  video_player: ^2.8.6
  connectivity_plus: ^5.0.1
  pdf: ^3.10.8
  open_file: ^3.3.2
  appinio_video_player:
  printing: ^5.12.0
  universal_html: ^2.2.4
  number_to_words_english: ^2.0.2

  flutter: 
    sdk: flutter
  path_provider: ^2.1.2
  path: ^1.9.0
 #  device_info_plus: ^10.1.0
#  package_info_plus: ^8.0.0
  #device_info: ^2.0.3
  firebase_messaging: ^14.8.2
  flutter_local_notifications: ^17.1.0
  googleapis_auth: ^1.6.0
  audioplayers: ^6.0.0
#  assets_audio_player: ^3.0.8

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/ringtone/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/OpenSans.ttf

